[package]
name = "slatedb-test-macros"
edition = "2021"
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
quote = { version = "1.0" }
syn = { version = "1.0", features = ["extra-traits", "full"] }
